// Copyright (c) 2025 Thorium

package commands

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"thorium-cli/internal/config"
)

// AddonType represents a type of addon that can be created
type AddonType string

const (
	AddonTypeBasic AddonType = "basic"
)

// CreateAddon creates a new addon in a mod's luaxml folder
func CreateAddon(cfg *config.Config, args []string) error {
	fs := flag.NewFlagSet("create-addon", flag.ExitOnError)
	modName := fs.String("mod", "", "Mod to create addon in (required)")
	fs.Parse(args)

	// Get addon name from remaining args
	remaining := fs.Args()
	if len(remaining) < 1 {
		return fmt.Errorf("usage: thorium create-addon --mod <mod> <addon-name>")
	}
	addonName := remaining[0]

	// Validate mod name
	if *modName == "" {
		return fmt.Errorf("--mod is required. Use: thorium create-addon --mod <mod> <addon-name>")
	}

	fmt.Println("=== Create Addon ===")
	fmt.Printf("Mod: %s\n", *modName)
	fmt.Printf("Addon: %s\n", addonName)
	fmt.Println()

	// Build addon path
	addonDir := filepath.Join(cfg.GetModsPath(), *modName, "luaxml", "Interface", "AddOns", addonName)

	// Check if addon already exists
	if _, err := os.Stat(addonDir); !os.IsNotExist(err) {
		return fmt.Errorf("addon already exists: %s", addonDir)
	}

	// Create addon directory
	if err := os.MkdirAll(addonDir, 0755); err != nil {
		return fmt.Errorf("create addon directory: %w", err)
	}

	// Generate addon files
	if err := createBasicAddon(addonDir, addonName); err != nil {
		return fmt.Errorf("create addon: %w", err)
	}

	fmt.Printf("✓ Addon created at: %s\n", addonDir)
	fmt.Println()
	fmt.Println("Files created:")
	filepath.Walk(addonDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		relPath, _ := filepath.Rel(addonDir, path)
		fmt.Printf("  - %s\n", relPath)
		return nil
	})

	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Edit the addon files as needed")
	fmt.Println("  2. Run 'thorium build' to package into MPQ")
	fmt.Println("  3. The addon will be available in-game")
	fmt.Println()
	fmt.Println("Note: CustomPackets API is available globally via the CustomPackets addon.")
	fmt.Println("      Use: ## Dependencies: CustomPackets in your TOC if needed.")

	return nil
}

// createBasicAddon creates a basic addon skeleton
func createBasicAddon(addonDir, addonName string) error {
	// Sanitize addon name for Lua variable use
	luaName := strings.ReplaceAll(addonName, "-", "_")
	luaName = strings.ReplaceAll(luaName, " ", "_")

	// Generate TOC file
	tocContent := fmt.Sprintf(`## Interface: 30300
## Title: %s
## Notes: A custom addon
## Author: Your Name
## Version: 1.0.0
## SavedVariables: %sDB

main.lua
`, addonName, luaName)

	tocPath := filepath.Join(addonDir, addonName+".toc")
	if err := os.WriteFile(tocPath, []byte(tocContent), 0644); err != nil {
		return fmt.Errorf("write TOC: %w", err)
	}

	// Generate main.lua
	mainContent := fmt.Sprintf(`-- %s Addon
-- Generated by Thorium on %s

local ADDON_NAME = "%s"
local %s = {}

-- Saved variables (persisted between sessions)
%sDB = %sDB or {}

-- Create main frame
local frame = CreateFrame("Frame", ADDON_NAME .. "Frame")

-- Register events
frame:RegisterEvent("ADDON_LOADED")
frame:RegisterEvent("PLAYER_LOGIN")
frame:RegisterEvent("PLAYER_LOGOUT")

-- Event handler
frame:SetScript("OnEvent", function(self, event, arg1, ...)
    if event == "ADDON_LOADED" and arg1 == ADDON_NAME then
        %s:OnLoad()
    elseif event == "PLAYER_LOGIN" then
        %s:OnLogin()
    elseif event == "PLAYER_LOGOUT" then
        %s:OnLogout()
    end
end)

-- Called when addon is loaded
function %s:OnLoad()
    print("|cFF00FF00" .. ADDON_NAME .. "|r v1.0.0 loaded")
    
    -- Initialize saved variables with defaults
    if not %sDB.initialized then
        %sDB.initialized = true
        %sDB.settings = {
            enabled = true,
        }
    end
end

-- Called when player logs in
function %s:OnLogin()
    -- Add your login code here
end

-- Called when player logs out
function %s:OnLogout()
    -- Add your logout/save code here
end

-- Slash command
SLASH_%s1 = "/%s"
SlashCmdList["%s"] = function(msg)
    local cmd, args = strsplit(" ", msg, 2)
    cmd = strlower(cmd or "")
    
    if cmd == "help" or cmd == "" then
        print("|cFF00FF00" .. ADDON_NAME .. "|r commands:")
        print("  /%s help - Show this help")
        print("  /%s toggle - Toggle addon on/off")
    elseif cmd == "toggle" then
        %sDB.settings.enabled = not %sDB.settings.enabled
        if %sDB.settings.enabled then
            print("|cFF00FF00" .. ADDON_NAME .. "|r enabled")
        else
            print("|cFFFF0000" .. ADDON_NAME .. "|r disabled")
        end
    end
end
`, addonName, time.Now().Format("2006-01-02"),
		addonName, luaName,
		luaName, luaName,
		luaName, luaName, luaName,
		luaName,
		luaName, luaName, luaName,
		luaName, luaName,
		strings.ToUpper(luaName), strings.ToLower(luaName), strings.ToUpper(luaName),
		strings.ToLower(luaName), strings.ToLower(luaName),
		luaName, luaName, luaName)

	mainPath := filepath.Join(addonDir, "main.lua")
	if err := os.WriteFile(mainPath, []byte(mainContent), 0644); err != nil {
		return fmt.Errorf("write main.lua: %w", err)
	}

	return nil
}
